"""Helpers for schedule configuration and GitHub Actions workflows."""
from __future__ import annotations

import csv
import io
import re
from typing import Any

CADENCES = ["Weekly", "Monthly", "Quarterly", "Yearly"]
WEEKDAYS = {
    "Monday": 1,
    "Tuesday": 2,
    "Wednesday": 3,
    "Thursday": 4,
    "Friday": 5,
    "Saturday": 6,
    "Sunday": 0,
}


def clean_id(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-").lower()
    return value or "dataset"


def cadence_to_cron(config: dict[str, Any]) -> str:
    minute = int(config.get("minute", 0))
    hour = int(config.get("hour_utc", 7))
    cadence = str(config.get("cadence", "Monthly"))
    day_of_month = int(config.get("day_of_month", 1))
    month = int(config.get("month", 1))
    weekday = WEEKDAYS.get(str(config.get("weekday", "Monday")), 1)
    if cadence == "Weekly":
        return f"{minute} {hour} * * {weekday}"
    if cadence == "Quarterly":
        return f"{minute} {hour} {day_of_month} 1,4,7,10 *"
    if cadence == "Yearly":
        return f"{minute} {hour} {day_of_month} {month} *"
    return f"{minute} {hour} {day_of_month} * *"


CONFIG_FIELDS = [
    "dataset_id",
    "dataset",
    "source",
    "recipient_name",
    "recipient_email",
    "cadence",
    "weekday",
    "day_of_month",
    "month",
    "hour_utc",
    "minute",
    "ai_summary",
    "cron",
]


def normalize_config(config: dict[str, Any]) -> dict[str, Any]:
    row = dict(config)
    row.setdefault("dataset_id", clean_id(str(row.get("dataset", "dataset"))))
    row["cron"] = cadence_to_cron(row)
    return {field: row.get(field, "") for field in CONFIG_FIELDS}


def configs_to_csv(configs: list[dict[str, Any]]) -> str:
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=CONFIG_FIELDS)
    writer.writeheader()
    for config in configs:
        writer.writerow(normalize_config(config))
    return output.getvalue()


def config_to_csv(config: dict[str, Any]) -> str:
    return configs_to_csv([config])


def build_workflow_yaml_for_crons(crons: list[str]) -> str:
    unique_crons: list[str] = []
    for cron in crons:
        if cron and cron not in unique_crons:
            unique_crons.append(cron)
    if not unique_crons:
        unique_crons = ["0 7 1 * *"]
    cron_lines = "\n".join(f'    - cron: "{cron}"' for cron in unique_crons)
    return f'''# Generated by Data Profiling Manager. GitHub Actions cron uses UTC.
name: Scheduled Data Profiling

on:
  schedule:
{cron_lines}
  workflow_dispatch:

jobs:
  profile-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run matching profiles
        shell: bash
        run: |
          if [ -n "${{{{ github.event.schedule }}}}" ]; then
            python monthly_profiling_agent.py --cron "${{{{ github.event.schedule }}}}"
          else
            python monthly_profiling_agent.py --all
          fi
        env:
          SMTP_HOST: ${{{{ secrets.SMTP_HOST }}}}
          SMTP_PORT: ${{{{ secrets.SMTP_PORT }}}}
          SMTP_USER: ${{{{ secrets.SMTP_USER }}}}
          SMTP_PASS: ${{{{ secrets.SMTP_PASS }}}}
          GEMINI_API_KEY: ${{{{ secrets.GEMINI_API_KEY }}}}
          GEMINI_MODEL: gemini-2.5-flash
      - name: Upload profiling outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-profiling-results-${{{{ github.run_id }}}}
          path: |
            scheduled_reports/
            run_log.jsonl
            profiling_history.jsonl
          if-no-files-found: ignore
          retention-days: 30
'''


def build_workflow_yaml(config: dict[str, Any]) -> str:
    return build_workflow_yaml_for_crons([cadence_to_cron(config)])
