"""Helpers for generating schedule configuration and GitHub Actions workflows."""
from __future__ import annotations

import csv
import io
import re
from typing import Any

CADENCES = ["Weekly", "Monthly", "Quarterly", "Yearly"]
WEEKDAYS = {
    "Monday": 1,
    "Tuesday": 2,
    "Wednesday": 3,
    "Thursday": 4,
    "Friday": 5,
    "Saturday": 6,
    "Sunday": 0,
}


def clean_id(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-").lower()
    return value or "dataset"


def cadence_to_cron(config: dict[str, Any]) -> str:
    minute = int(config.get("minute", 0))
    hour = int(config.get("hour_utc", 7))
    cadence = config.get("cadence", "Monthly")
    day_of_month = int(config.get("day_of_month", 1))
    month = int(config.get("month", 1))
    weekday = WEEKDAYS.get(str(config.get("weekday", "Monday")), 1)

    if cadence == "Weekly":
        return f"{minute} {hour} * * {weekday}"
    if cadence == "Quarterly":
        return f"{minute} {hour} {day_of_month} 1,4,7,10 *"
    if cadence == "Yearly":
        return f"{minute} {hour} {day_of_month} {month} *"
    return f"{minute} {hour} {day_of_month} * *"


def config_to_csv(config: dict[str, Any]) -> str:
    fields = [
        "dataset_id",
        "dataset",
        "source",
        "recipient_name",
        "recipient_email",
        "cadence",
        "weekday",
        "day_of_month",
        "month",
        "hour_utc",
        "minute",
        "ai_summary",
        "cron",
    ]
    row = dict(config)
    row.setdefault("dataset_id", clean_id(str(row.get("dataset", "dataset"))))
    row["cron"] = cadence_to_cron(row)
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fields)
    writer.writeheader()
    writer.writerow({field: row.get(field, "") for field in fields})
    return output.getvalue()


def build_workflow_yaml(config: dict[str, Any]) -> str:
    cron = cadence_to_cron(config)
    return f'''# Generated by Data Profiling Manager.
# Save as .github/workflows/scheduled_profiling.yml in your own repository.
# GitHub Actions cron uses UTC.
name: Scheduled Data Profiling

on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:

jobs:
  profile-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python monthly_profiling_agent.py --cron "${{{{ github.event.schedule }}}}"
        env:
          SMTP_HOST: ${{{{ secrets.SMTP_HOST }}}}
          SMTP_PORT: ${{{{ secrets.SMTP_PORT }}}}
          SMTP_USER: ${{{{ secrets.SMTP_USER }}}}
          SMTP_PASS: ${{{{ secrets.SMTP_PASS }}}}
          GEMINI_API_KEY: ${{{{ secrets.GEMINI_API_KEY }}}}
          GEMINI_MODEL: gemini-2.5-flash
'''
