import { cadenceToCron } from './monitoring';
import type { DatabaseConnection, DatabaseProvider, WorkspaceSnapshot } from './types';

export function defaultDatabasePort(provider: DatabaseProvider): number {
  if (provider === 'DB2') return 50000;
  if (provider === 'Snowflake') return 443;
  return 5432;
}

export function normalizeSecretPrefix(value: string): string {
  return value.trim().toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'DPM_DATABASE';
}

export function requiredEnvironmentVariables(connection: DatabaseConnection): string[] {
  const prefix = normalizeSecretPrefix(connection.secretPrefix);
  return [`${prefix}_USER`, `${prefix}_PASSWORD`];
}

export function isReadOnlyQuery(query: string): boolean {
  const stripped = query.replace(/--.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '').trim();
  if (!/^(select|with)\b/i.test(stripped)) return false;
  const withoutTrailingSemicolon = stripped.replace(/;\s*$/, '');
  if (withoutTrailingSemicolon.includes(';')) return false;
  return !/\b(insert|update|delete|drop|alter|create|truncate|merge|call|execute|grant|revoke|copy|put|remove)\b/i.test(withoutTrailingSemicolon);
}

export function connectorConfigJson(workspace: WorkspaceSnapshot): string {
  return JSON.stringify({
    version: 1,
    exportedAt: new Date().toISOString(),
    connections: (workspace.connections ?? []).filter((connection) => connection.enabled).map(({ id, datasetId, name, provider, host, port, database, schema, account, warehouse, role, sslMode, secretPrefix, query, maxRows, enabled }) => ({
      id, datasetId, name, provider, host, port, database, schema, account, warehouse, role, sslMode, secretPrefix: normalizeSecretPrefix(secretPrefix), query, maxRows, enabled,
    })),
  }, null, 2);
}

export function buildDatabaseScheduledWorkflow(workspace: WorkspaceSnapshot): string {
  const activeConnections = (workspace.connections ?? []).filter((connection) => connection.enabled);
  const connectionIds = new Set(activeConnections.map((connection) => connection.id));
  const policies = (workspace.monitors ?? []).filter((policy) => policy.enabled && policy.sourcePath.startsWith('connection:') && connectionIds.has(policy.sourcePath.slice('connection:'.length)));
  const crons = [...new Set(policies.map(cadenceToCron))];
  const scheduleBlock = crons.length ? `  schedule:\n${crons.map((cron) => `    - cron: "${cron}"`).join('\n')}\n` : '';
  const databaseSecrets = [...new Set(activeConnections.flatMap(requiredEnvironmentVariables))].map((name) => `          ${name}: \${{ secrets.${name} }}`).join('\n');
  return `# Generated by Data Profiling Manager.
# Database workflows default to a self-hosted Linux runner so private company databases are not exposed to a public runner.
name: Scheduled Database Profiling

on:
${scheduleBlock}  workflow_dispatch:

jobs:
  profile-databases:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt -r requirements-connectors.txt
      - name: Run matching database profiles
        shell: bash
        run: |
          if [ -n "\${{ github.event.schedule }}" ]; then
            python database_scheduled_agent.py --cron "\${{ github.event.schedule }}"
          else
            python database_scheduled_agent.py --all
          fi
        env:
          SMTP_HOST: \${{ secrets.SMTP_HOST }}
          SMTP_PORT: \${{ secrets.SMTP_PORT }}
          SMTP_USER: \${{ secrets.SMTP_USER }}
          SMTP_PASS: \${{ secrets.SMTP_PASS }}
          GEMINI_API_KEY: \${{ secrets.GEMINI_API_KEY }}
${databaseSecrets}
      - name: Upload profiling outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: database-profiling-results-\${{ github.run_id }}
          path: |
            scheduled_reports/
            run_log.jsonl
            profiling_history.jsonl
          if-no-files-found: ignore
          retention-days: 7
`;
}