import { recordComplianceScore } from './scoring';
import type { Dataset, MonitorPolicy, ProfileRun, WorkspaceSnapshot } from './types';

const WEEKDAYS: Record<string, number> = { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 };

export function cadenceToCron(policy: MonitorPolicy): string {
  const minute = Math.min(59, Math.max(0, policy.minute));
  const hour = Math.min(23, Math.max(0, policy.hourUtc));
  const day = Math.min(28, Math.max(1, policy.dayOfMonth));
  const month = Math.min(12, Math.max(1, policy.month));
  if (policy.cadence === 'Weekly') return `${minute} ${hour} * * ${WEEKDAYS[policy.weekday] ?? 1}`;
  if (policy.cadence === 'Quarterly') return `${minute} ${hour} ${day} 1,4,7,10 *`;
  if (policy.cadence === 'Yearly') return `${minute} ${hour} ${day} ${month} *`;
  return `${minute} ${hour} ${day} * *`;
}

function csvValue(value: unknown): string {
  const text = value === undefined || value === null ? '' : String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function policiesToCsv(policies: MonitorPolicy[], datasets: Dataset[]): string {
  const fields = [
    'dataset_id', 'dataset', 'source', 'recipient_name', 'recipient_email', 'cc_emails', 'cadence', 'weekday',
    'day_of_month', 'month', 'hour_utc', 'minute', 'delivery_mode', 'attach_report', 'ai_summary',
    'minimum_overall_quality', 'minimum_record_compliance', 'maximum_missing_percent', 'maximum_duplicate_rows',
    'maximum_row_change_percent', 'maximum_freshness_hours', 'cron',
  ];
  const rows = policies.filter((policy) => policy.enabled).map((policy) => {
    const dataset = datasets.find((item) => item.id === policy.datasetId);
    return [
      policy.datasetId, dataset?.name ?? policy.datasetId, policy.sourcePath, policy.recipientName, policy.recipientEmail,
      policy.ccEmails ?? '', policy.cadence, policy.weekday, policy.dayOfMonth, policy.month, policy.hourUtc, policy.minute,
      policy.deliveryMode, policy.attachReport, policy.aiSummary, policy.minimumOverallQuality, policy.minimumRecordCompliance,
      policy.maximumMissingPercent, policy.maximumDuplicateRows, policy.maximumRowChangePercent, policy.maximumFreshnessHours,
      cadenceToCron(policy),
    ];
  });
  return [fields, ...rows].map((row) => row.map(csvValue).join(',')).join('\n');
}

export function qualityConfigJson(workspace: WorkspaceSnapshot): string {
  return JSON.stringify({
    version: 1,
    exportedAt: new Date().toISOString(),
    dimensions: (workspace.dimensions ?? []).map(({ id, name, description, weight, enabled, source }) => ({ id, name, description, weight, enabled, source })),
    rules: workspace.rules.map(({ id, datasetId, name, dimension, columnName, ruleType, expectedValue, secondaryValue, enabled, weight, threshold, severity }) => ({ id, datasetId, name, dimension, columnName, ruleType, expectedValue, secondaryValue, enabled, weight, threshold, severity })),
  }, null, 2);
}

export function buildScheduledWorkflow(policies: MonitorPolicy[]): string {
  const crons = [...new Set(policies.filter((policy) => policy.enabled).map(cadenceToCron))];
  const schedules = (crons.length ? crons : ['0 7 1 * *']).map((cron) => `    - cron: "${cron}"`).join('\n');
  return `# Generated by Data Profiling Manager. GitHub Actions cron uses UTC.
name: Scheduled Data Profiling

on:
  schedule:
${schedules}
  workflow_dispatch:

jobs:
  profile-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run matching profiles
        shell: bash
        run: |
          if [ -n "\${{ github.event.schedule }}" ]; then
            python monthly_profiling_agent.py --cron "\${{ github.event.schedule }}"
          else
            python monthly_profiling_agent.py --all
          fi
        env:
          SMTP_HOST: \${{ secrets.SMTP_HOST }}
          SMTP_PORT: \${{ secrets.SMTP_PORT }}
          SMTP_USER: \${{ secrets.SMTP_USER }}
          SMTP_PASS: \${{ secrets.SMTP_PASS }}
          GEMINI_API_KEY: \${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash
      - name: Upload profiling outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-profiling-results-\${{ github.run_id }}
          path: |
            scheduled_reports/
            run_log.jsonl
            profiling_history.jsonl
          if-no-files-found: ignore
          retention-days: 30
`;
}

export function monitorBreaches(policy: MonitorPolicy, latest?: ProfileRun, previous?: ProfileRun): string[] {
  if (!latest) return ['No profiling run exists yet.'];
  const breaches: string[] = [];
  if (policy.minimumOverallQuality !== undefined && latest.quality.overallScore < policy.minimumOverallQuality) breaches.push(`Overall quality ${latest.quality.overallScore.toFixed(1)}% is below ${policy.minimumOverallQuality.toFixed(1)}%.`);
  const compliance = recordComplianceScore(latest.quality);
  if (policy.minimumRecordCompliance !== undefined && compliance < policy.minimumRecordCompliance) breaches.push(`Strict record compliance ${compliance.toFixed(1)}% is below ${policy.minimumRecordCompliance.toFixed(1)}%.`);
  if (policy.maximumMissingPercent !== undefined && latest.missingPercentage > policy.maximumMissingPercent) breaches.push(`Missing cells ${latest.missingPercentage.toFixed(1)}% exceed ${policy.maximumMissingPercent.toFixed(1)}%.`);
  if (policy.maximumDuplicateRows !== undefined && latest.duplicateRows > policy.maximumDuplicateRows) breaches.push(`${latest.duplicateRows.toLocaleString()} duplicate rows exceed ${policy.maximumDuplicateRows.toLocaleString()}.`);
  if (policy.maximumRowChangePercent !== undefined && previous?.rowCount) {
    const change = Math.abs((latest.rowCount - previous.rowCount) / previous.rowCount * 100);
    if (change > policy.maximumRowChangePercent) breaches.push(`Row count changed ${change.toFixed(1)}%, above ${policy.maximumRowChangePercent.toFixed(1)}%.`);
  }
  if (policy.maximumFreshnessHours !== undefined) {
    const age = (Date.now() - new Date(latest.createdAt).getTime()) / 3_600_000;
    if (age > policy.maximumFreshnessHours) breaches.push(`Latest successful run is ${age.toFixed(1)} hours old, above ${policy.maximumFreshnessHours.toFixed(1)} hours.`);
  }
  return breaches;
}
